---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task
    username: ((DOCKER_HUB_SKYSCRAPERS_CREDS.username))
    password: ((DOCKER_HUB_SKYSCRAPERS_CREDS.password))

inputs:
  - name: context
    path: .
  - name: args
    path: args/
    optional: true
  - name: docker_creds
    optional: true

outputs:
  - name: image

params:
  CONTEXT:
  BUILD_ARGS_FILE:
  DOCKER_CONFIG:

caches:
  - path: cache

run: { path: build }
